import { takeEvery, takeLatest, all } from 'redux-saga/effects'
import { AppTypes } from '~/actions/app'
import { DevTypes } from '~/actions/develop'
import { MngTypes } from '~/actions/manage'
import { VenTypes } from '~/actions/vendor'
import { CompanyTypes } from '~/actions/company'
import { CommunityTypes } from '~/actions/community'
import API from '~/services/api'

import {
  loginRequest,
  logoutRequest,
  getauthorsRequest,
  fetchcompanyvendorRequest,
  libraryfiltersRequest,
  uploadRequest,
  globalcompaniesRequest,
  getcompanyRequest,
  posteditprofileRequest,
  postuploadavatarRequest,
  postcompanyusersRequest,
  fetchnotificationsRequest,
  updatenotificationsRequest,
  advancedsearchRequest,
  postcompanyemployeesRequest,
  postrecoverypasswordRequest,
  postmulticompanydataRequest,
  getallauthorsRequest,
  postsaveauthorRequest,
  postsavebusinessauthorRequest,
  postdeleteauthorRequest,
  getcommunityusersRequest,
  getuserconnectionsRequest,
} from './app'
import {
  fetchfeedsRequest,
  dailytrainingRequest,
  librarytemplatesRequest,
  librarytemplatesaveRequest,
  librarycardtemplatesRequest,
  libraryeventRequest,
  librarytrackdetailRequest,
  libraryprogramdetailRequest,
  quotatemplatesRequest,
  trainingscheduledetailRequest,
  librarysaveRequest,
  questionRequest,
  answerRequest,
  resetquizRequest,
  createquotaRequest,
  getquotaoptionsRequest,
  adddocumentRequest,
  careergoalsRequest,
  careergoalsaveRequest,
  careerdevreportsRequest,
  careertasksRequest,
  careertrainingsRequest,
  userscoursereportRequest,
  teamreportsRequest,
  traininglistRequest,
  updatemoduleRequest,
  updatecardRequest,
  updatecardinstanceRequest,
  careerpromoteRequest,
  careerApprovalTaskRequest,
  adddevcommentRequest,
  postcompanyinfoRequest,
  fetchnotificationssettingsRequest,
  updatenotificationssettingsRequest,
  programeventRequest,
  programpromotionRequest,
  postscorecardsaveRequest,
  postdeletescorecardRequest,
  postterminateuserRequest,
  postdeleteuserRequest,
} from './develop'
import {
  getcareerprogramRequest,
  postcareerprogramRequest,
  fetchtasksfeedRequest,
  companyprojectsRequest,
  selectprojectRequest,
  edittaskRequest,
  deletetaskRequest,
  fetchtaskdetailRequest,
  selectusersRequest,
  userprojecttaskRequest,
  addmngcommentRequest,
  addtaskRequest,
  fetchauthorsRequest,
  searchmodulesRequest,
  assigncoursesRequest,
  assigntrainingRequest,
  unassigncontentRequest,
  fetchcompanycareersRequest,
  fetchprojectsdetailRequest,
  updatetaskRequest,
  addprojectRequest,
  updateprojectRequest,
  deleteprojectRequest,
  companyindividualRequest,
  fetchengagementreportRequest,
  fetchcertificationsreportRequest,
  fetchcareerreportsRequest,
  fetchhireorientationreportRequest,
  companyperformancereviewsRequest,
  individualperformancereviewRequest,
  postperformancereviewRequest,
  getperformancereviewsRequest,
  getpreviousreviewtasksRequest,
  getmanagerdashboardRequest,
  postquotaactualsRequest,
  getanniversarybirthdayRequest,
  posttrainingreportsRequest,
  postquotaactualcommentRequest,
  postsignoffRequest,
  postquotareportRequest,
  posttrainingcompetencyreportRequest,
  postterminateemployeeRequest,
  postindividualquotareportRequest,
  getquotasactualsRequest,
} from './manage'

import {
  getcategoriesRequest,
  getcategorypopularproductsRequest,
  getcategoryproductsRequest,
  getcompanyadminsRequest,
  getvendorcompanyRequest,
  getvendorcompaniesRequest,
  savevendorratingRequest,
  getvendorawardsRequest,
  getrecentlyupdatedproductsRequest,
  getpopularproductsRequest,
  globalsearchRequest,
  savevrproductRequest,
  savevrcompanyRequest,
  savevrphotoRequest,
  getvrcompanyRequest,
  postvrcompanyadminRequest,
  postblogadminRequest,
  getblogRequest,
  saveblogRequest,
  getblogpostsRequest,
  saveblogpostRequest,
  deleteblogpostRequest,
  postadduserRequest,
  postremoveuserRequest,
  postsaveproductRequest,
  postsaveproductmediaRequest,
} from './vendor'

import {
  postcreateblogRequest,
  addforumtopicRequest,
  getforumindividualtopicRequest,
  addtopiccommentRequest,
  editforumtopicRequest,
  getcommunityblogRequest,
  getblogsummaryRequest,
  getblogdetailsRequest,
  getcommunityuserRequest,
  getcommunityconnectionsRequest,
  postcommunityconnectRequest,
  getuserpermissionsRequest,
  postpasswordchangeRequest,
  postunfollowRequest,
  postconnectionupdateRequest,
  postcommunityuserRequest,
  postregisteruserRequest,
  gettopicsRequest,
  getcomblogpostsRequest,
  geteditfeatureditemsRequest,
  getfeatureditemsRequest,
  getcategorysponsoredproductsRequest,
  postsavecommentRequest,
} from './community'

import {
  getbusinessRequest,
  postbusinessRequest,
  getbusinessblogRequest,
  getbzcompanyRequest,
  savebzcompanyRequest,
  savebusinessRequest,
  getblogcategoriesRequest,
  gettopiccategoriesRequest,
  getcompanyusersRequest,
  postregisterbusinessuserRequest,
  postaddeditdepartmentsRequest,
  postaddeditteamsRequest,
  postsavejobrolesRequest,
  postsavehcmcompanyRequest,
  getcompanyemployeesRequest,
} from './company'

const api = API.create()

export default function* root() {
  yield all([
    takeLatest(AppTypes.LOGIN_REQUEST, loginRequest, api),
    takeLatest(AppTypes.LOGOUT_REQUEST, logoutRequest, api),
    takeLatest(AppTypes.GETAUTHORS_REQUEST, getauthorsRequest, api),
    takeLatest(AppTypes.GETUSERCONNECTIONS_REQUEST, getuserconnectionsRequest, api),
    takeLatest(AppTypes.FETCHCOMPANYVENDOR_REQUEST, fetchcompanyvendorRequest, api),
    takeLatest(AppTypes.LIBRARYFILTERS_REQUEST, libraryfiltersRequest, api),
    takeLatest(AppTypes.UPLOAD_REQUEST, uploadRequest, api),
    takeLatest(AppTypes.GLOBALCOMPANIES_REQUEST, globalcompaniesRequest, api),
    takeLatest(AppTypes.GETCOMPANY_REQUEST, getcompanyRequest, api),
    takeLatest(AppTypes.POSTEDITPROFILE_REQUEST, posteditprofileRequest, api),
    takeLatest(AppTypes.POSTUPLOADAVATAR_REQUEST, postuploadavatarRequest, api),
    takeLatest(AppTypes.POSTCOMPANYUSERS_REQUEST, postcompanyusersRequest, api),
    takeLatest(AppTypes.FETCHNOTIFICATIONS_REQUEST, fetchnotificationsRequest, api),
    takeLatest(AppTypes.UPDATENOTIFICATIONS_REQUEST, updatenotificationsRequest, api),
    takeLatest(AppTypes.ADVANCEDSEARCH_REQUEST, advancedsearchRequest, api),
    takeLatest(AppTypes.POSTCOMPANYEMPLOYEES_REQUEST, postcompanyemployeesRequest, api),
    takeLatest(AppTypes.POSTRECOVERYPASSWORD_REQUEST, postrecoverypasswordRequest, api),
    takeLatest(AppTypes.POSTMULTICOMPANYDATA_REQUEST, postmulticompanydataRequest, api),
    takeLatest(AppTypes.GETALLAUTHORS_REQUEST, getallauthorsRequest, api),
    takeLatest(AppTypes.POSTSAVEAUTHOR_REQUEST, postsaveauthorRequest, api),
    takeLatest(AppTypes.POSTSAVEBUSINESSAUTHOR_REQUEST, postsavebusinessauthorRequest, api),
    takeLatest(AppTypes.POSTDELETEAUTHOR_REQUEST, postdeleteauthorRequest, api),
    takeLatest(AppTypes.GETCOMMUNITYUSERS_REQUEST, getcommunityusersRequest, api),

    takeLatest(DevTypes.FETCHFEEDS_REQUEST, fetchfeedsRequest, api),
    takeLatest(DevTypes.DAILYTRAINING_REQUEST, dailytrainingRequest, api),
    takeLatest(DevTypes.UPDATECARD_REQUEST, updatecardRequest, api),
    takeLatest(DevTypes.POSTSCORECARDSAVE_REQUEST, postscorecardsaveRequest, api),
    takeLatest(DevTypes.POSTDELETESCORECARD_REQUEST, postdeletescorecardRequest, api),
    takeLatest(DevTypes.UPDATECARDINSTANCE_REQUEST, updatecardinstanceRequest, api),
    takeLatest(DevTypes.LIBRARYTEMPLATES_REQUEST, librarytemplatesRequest, api),
    takeLatest(DevTypes.LIBRARYTEMPLATESAVE_REQUEST, librarytemplatesaveRequest, api),
    takeLatest(DevTypes.LIBRARYCARDTEMPLATES_REQUEST, librarycardtemplatesRequest, api),
    takeLatest(DevTypes.LIBRARYEVENT_REQUEST, libraryeventRequest, api),
    takeLatest(DevTypes.LIBRARYTRACKDETAIL_REQUEST, librarytrackdetailRequest, api),
    takeLatest(DevTypes.LIBRARYPROGRAMDETAIL_REQUEST, libraryprogramdetailRequest, api),
    takeLatest(DevTypes.QUOTATEMPLATES_REQUEST, quotatemplatesRequest, api),
    takeLatest(DevTypes.TRAININGSCHEDULEDETAIL_REQUEST, trainingscheduledetailRequest, api),
    takeLatest(DevTypes.LIBRARYSAVE_REQUEST, librarysaveRequest, api),
    takeLatest(DevTypes.QUESTION_REQUEST, questionRequest, api),
    takeLatest(DevTypes.ANSWER_REQUEST, answerRequest, api),
    takeLatest(DevTypes.RESETQUIZ_REQUEST, resetquizRequest, api),
    takeLatest(DevTypes.CREATEQUOTA_REQUEST, createquotaRequest, api),
    takeLatest(DevTypes.GETQUOTAOPTIONS_REQUEST, getquotaoptionsRequest, api),
    takeLatest(DevTypes.ADDDOCUMENT_REQUEST, adddocumentRequest, api),
    takeLatest(DevTypes.CAREERGOALS_REQUEST, careergoalsRequest, api),
    takeLatest(DevTypes.CAREERGOALSAVE_REQUEST, careergoalsaveRequest, api),
    takeLatest(DevTypes.CAREERDEVREPORTS_REQUEST, careerdevreportsRequest, api),
    takeLatest(DevTypes.CAREERTASKS_REQUEST, careertasksRequest, api),
    takeLatest(DevTypes.CAREERTRAININGS_REQUEST, careertrainingsRequest, api),
    takeLatest(DevTypes.USERSCOURSEREPORT_REQUEST, userscoursereportRequest, api),
    takeLatest(DevTypes.TEAMREPORTS_REQUEST, teamreportsRequest, api),
    takeLatest(DevTypes.TRAININGLIST_REQUEST, traininglistRequest, api),
    takeLatest(DevTypes.UPDATEMODULE_REQUEST, updatemoduleRequest, api),
    takeLatest(DevTypes.CAREERPROMOTE_REQUEST, careerpromoteRequest, api),
    takeLatest(DevTypes.CAREERCARD_REQUEST, careerApprovalTaskRequest, api),
    takeLatest(DevTypes.ADDDEVCOMMENT_REQUEST, adddevcommentRequest, api),
    takeLatest(DevTypes.POSTCOMPANYINFO_REQUEST, postcompanyinfoRequest, api),
    takeLatest(DevTypes.FETCHNOTIFICATIONSSETTINGS_REQUEST, fetchnotificationssettingsRequest, api),
    takeLatest(DevTypes.UPDATENOTIFICATIONSSETTINGS_REQUEST, updatenotificationssettingsRequest, api),
    takeLatest(DevTypes.PROGRAMEVENT_REQUEST, programeventRequest, api),
    takeLatest(DevTypes.PROGRAMPROMOTION_REQUEST, programpromotionRequest, api),
    takeLatest(DevTypes.POSTTERMINATEUSER_REQUEST, postterminateuserRequest, api),
    takeLatest(DevTypes.POSTDELETEUSER_REQUEST, postdeleteuserRequest, api),

    takeLatest(MngTypes.GETCAREERPROGRAM_REQUEST, getcareerprogramRequest, api),
    takeLatest(MngTypes.POSTCAREERPROGRAM_REQUEST, postcareerprogramRequest, api),
    takeLatest(MngTypes.FETCHTASKSFEED_REQUEST, fetchtasksfeedRequest, api),
    takeLatest(MngTypes.COMPANYPROJECTS_REQUEST, companyprojectsRequest, api),
    takeLatest(MngTypes.SELECTPROJECT_REQUEST, selectprojectRequest, api),
    takeLatest(MngTypes.EDITTASK_REQUEST, edittaskRequest, api),
    takeLatest(MngTypes.DELETETASK_REQUEST, deletetaskRequest, api),
    takeLatest(MngTypes.FETCHTASKDETAIL_REQUEST, fetchtaskdetailRequest, api),
    takeLatest(MngTypes.SELECTUSERS_REQUEST, selectusersRequest, api),
    takeEvery(MngTypes.USERPROJECTTASK_REQUEST, userprojecttaskRequest, api),
    takeEvery(MngTypes.ADDMNGCOMMENT_REQUEST, addmngcommentRequest, api),
    takeLatest(MngTypes.ADDTASK_REQUEST, addtaskRequest, api),
    takeLatest(MngTypes.FETCHAUTHORS_REQUEST, fetchauthorsRequest, api),
    takeLatest(MngTypes.SEARCHMODULES_REQUEST, searchmodulesRequest, api),
    takeLatest(MngTypes.ASSIGNCOURSES_REQUEST, assigncoursesRequest, api),
    takeLatest(MngTypes.ASSIGNTRAINING_REQUEST, assigntrainingRequest, api),
    takeLatest(MngTypes.UNASSIGNCONTENT_REQUEST, unassigncontentRequest, api),
    takeLatest(MngTypes.FETCHPROJECTSDETAIL_REQUEST, fetchprojectsdetailRequest, api),
    takeLatest(MngTypes.UPDATETASK_REQUEST, updatetaskRequest, api),
    takeLatest(MngTypes.ADDPROJECT_REQUEST, addprojectRequest, api),
    takeLatest(MngTypes.UPDATEPROJECT_REQUEST, updateprojectRequest, api),
    takeLatest(MngTypes.DELETEPROJECT_REQUEST, deleteprojectRequest, api),
    takeLatest(MngTypes.COMPANYINDIVIDUAL_REQUEST, companyindividualRequest, api),
    takeLatest(MngTypes.FETCHENGAGEMENTREPORT_REQUEST, fetchengagementreportRequest, api),
    takeLatest(MngTypes.FETCHCERTIFICATIONSREPORT_REQUEST, fetchcertificationsreportRequest, api),
    takeLatest(MngTypes.FETCHCAREERREPORTS_REQUEST, fetchcareerreportsRequest, api),
    takeLatest(MngTypes.FETCHHIREORIENTATIONREPORT_REQUEST, fetchhireorientationreportRequest, api),
    takeLatest(MngTypes.FETCHCOMPANYCAREERS_REQUEST, fetchcompanycareersRequest, api),
    takeLatest(MngTypes.COMPANYPERFORMANCEREVIEWS_REQUEST, companyperformancereviewsRequest, api),
    takeLatest(MngTypes.INDIVIDUALPERFORMANCEREVIEW_REQUEST, individualperformancereviewRequest, api),
    takeLatest(MngTypes.GETPERFORMANCEREVIEWS_REQUEST, getperformancereviewsRequest, api),
    takeLatest(MngTypes.GETPREVIOUSREVIEWTASKS_REQUEST, getpreviousreviewtasksRequest, api),
    takeLatest(MngTypes.POSTPERFORMANCEREVIEW_REQUEST, postperformancereviewRequest, api),
    takeLatest(MngTypes.GETMANAGERDASHBOARD_REQUEST, getmanagerdashboardRequest, api),
    takeLatest(MngTypes.POSTQUOTAACTUALS_REQUEST, postquotaactualsRequest, api),
    takeLatest(MngTypes.GETANNIVERSARYBIRTHDAY_REQUEST, getanniversarybirthdayRequest, api),
    takeLatest(MngTypes.POSTTRAININGREPORTS_REQUEST, posttrainingreportsRequest, api),
    takeLatest(MngTypes.POSTQUOTAACTUALCOMMENT_REQUEST, postquotaactualcommentRequest, api),
    takeLatest(MngTypes.POSTSIGNOFF_REQUEST, postsignoffRequest, api),
    takeLatest(MngTypes.POSTQUOTAREPORT_REQUEST, postquotareportRequest, api),
    takeLatest(MngTypes.POSTTRAININGCOMPETENCYREPORT_REQUEST, posttrainingcompetencyreportRequest, api),
    takeLatest(MngTypes.POSTTERMINATEEMPLOYEE_REQUEST, postterminateemployeeRequest, api),
    takeLatest(MngTypes.POSTINDIVIDUALQUOTAREPORT_REQUEST, postindividualquotareportRequest, api),
    takeLatest(MngTypes.GETQUOTASACTUALS_REQUEST, getquotasactualsRequest, api),

    takeLatest(VenTypes.GETCATEGORIES_REQUEST, getcategoriesRequest, api),
    takeEvery(VenTypes.GETCATEGORYPOPULARPRODUCTS_REQUEST, getcategorypopularproductsRequest, api),
    takeEvery(VenTypes.GETCATEGORYPRODUCTS_REQUEST, getcategoryproductsRequest, api),
    takeLatest(VenTypes.GETVENDORCOMPANY_REQUEST, getvendorcompanyRequest, api),
    takeLatest(VenTypes.GETCOMPANYADMINS_REQUEST, getcompanyadminsRequest, api),
    takeLatest(VenTypes.GETVENDORCOMPANIES_REQUEST, getvendorcompaniesRequest, api),
    takeLatest(VenTypes.POSTVRCOMPANYADMIN_REQUEST, postvrcompanyadminRequest, api),
    takeLatest(VenTypes.POSTBLOGADMIN_REQUEST, postblogadminRequest, api),
    takeLatest(VenTypes.SAVEVENDORRATING_REQUEST, savevendorratingRequest, api),
    takeLatest(VenTypes.GETVENDORAWARDS_REQUEST, getvendorawardsRequest, api),
    takeLatest(VenTypes.GETRECENTLYUPDATEDPRODUCTS_REQUEST, getrecentlyupdatedproductsRequest, api),
    takeLatest(VenTypes.GETPOPULARPRODUCTS_REQUEST, getpopularproductsRequest, api),
    takeLatest(VenTypes.GLOBALSEARCH_REQUEST, globalsearchRequest, api),
    takeLatest(VenTypes.SAVEVRPRODUCT_REQUEST, savevrproductRequest, api),
    takeLatest(VenTypes.SAVEVRCOMPANY_REQUEST, savevrcompanyRequest, api),
    takeLatest(VenTypes.SAVEVRPHOTO_REQUEST, savevrphotoRequest, api),
    takeLatest(VenTypes.GETVRCOMPANY_REQUEST, getvrcompanyRequest, api),
    takeLatest(VenTypes.GETBLOG_REQUEST, getblogRequest, api),
    takeLatest(VenTypes.SAVEBLOG_REQUEST, saveblogRequest, api),
    takeLatest(VenTypes.GETBLOGPOSTS_REQUEST, getblogpostsRequest, api),
    takeLatest(VenTypes.SAVEBLOGPOST_REQUEST, saveblogpostRequest, api),
    takeLatest(VenTypes.DELETEBLOGPOST_REQUEST, deleteblogpostRequest, api),
    takeLatest(VenTypes.POSTADDUSER_REQUEST, postadduserRequest, api),
    takeLatest(VenTypes.POSTREMOVEUSER_REQUEST, postremoveuserRequest, api),
    takeLatest(VenTypes.POSTSAVEPRODUCT_REQUEST, postsaveproductRequest, api),
    takeLatest(VenTypes.POSTSAVEPRODUCTMEDIA_REQUEST, postsaveproductmediaRequest, api),

    takeLatest(CompanyTypes.GETBUSINESS_REQUEST, getbusinessRequest, api),
    takeLatest(CompanyTypes.POSTBUSINESS_REQUEST, postbusinessRequest, api),
    takeLatest(CompanyTypes.GETBUSINESSBLOG_REQUEST, getbusinessblogRequest, api),
    takeLatest(CompanyTypes.GETBZCOMPANY_REQUEST, getbzcompanyRequest, api),
    takeLatest(CompanyTypes.SAVEBZCOMPANY_REQUEST, savebzcompanyRequest, api),
    takeLatest(CompanyTypes.SAVEBUSINESS_REQUEST, savebusinessRequest, api),
    takeLatest(CompanyTypes.GETBLOGCATEGORIES_REQUEST, getblogcategoriesRequest, api),
    takeLatest(CompanyTypes.GETTOPICCATEGORIES_REQUEST, gettopiccategoriesRequest, api),
    takeLatest(CompanyTypes.GETCOMPANYUSERS_REQUEST, getcompanyusersRequest, api),
    takeLatest(CompanyTypes.POSTREGISTERBUSINESSUSER_REQUEST, postregisterbusinessuserRequest, api),
    takeLatest(CompanyTypes.POSTADDEDITDEPARTMENTS_REQUEST, postaddeditdepartmentsRequest, api),
    takeLatest(CompanyTypes.POSTADDEDITTEAMS_REQUEST, postaddeditteamsRequest, api),
    takeLatest(CompanyTypes.POSTSAVEJOBROLES_REQUEST, postsavejobrolesRequest, api),
    takeLatest(CompanyTypes.POSTSAVEHCMCOMPANY_REQUEST, postsavehcmcompanyRequest, api),
    takeLatest(CompanyTypes.GETCOMPANYEMPLOYEES_REQUEST, getcompanyemployeesRequest, api),

    takeLatest(CommunityTypes.ADDFORUMTOPIC_REQUEST, addforumtopicRequest, api),
    takeLatest(CommunityTypes.POSTCREATEBLOG_REQUEST, postcreateblogRequest, api),
    takeLatest(CommunityTypes.GETFORUMINDIVIDUALTOPIC_REQUEST, getforumindividualtopicRequest, api),
    takeLatest(CommunityTypes.ADDTOPICCOMMENT_REQUEST, addtopiccommentRequest, api),
    takeLatest(CommunityTypes.EDITFORUMTOPIC_REQUEST, editforumtopicRequest, api),
    takeLatest(CommunityTypes.GETBLOGSUMMARY_REQUEST, getblogsummaryRequest, api),
    takeLatest(CommunityTypes.GETBLOGDETAILS_REQUEST, getblogdetailsRequest, api),
    takeLatest(CommunityTypes.GETCOMMUNITYUSER_REQUEST, getcommunityuserRequest, api),
    takeLatest(CommunityTypes.GETCOMMUNITYBLOG_REQUEST, getcommunityblogRequest, api),
    takeLatest(CommunityTypes.GETCOMMUNITYCONNECTIONS_REQUEST, getcommunityconnectionsRequest, api),
    takeLatest(CommunityTypes.POSTCOMMUNITYCONNECT_REQUEST, postcommunityconnectRequest, api),
    takeLatest(CommunityTypes.GETUSERPERMISSIONS_REQUEST, getuserpermissionsRequest, api),
    takeLatest(CommunityTypes.POSTCOMMUNITYUSER_REQUEST, postcommunityuserRequest, api),
    takeLatest(CommunityTypes.POSTPASSWORDCHANGE_REQUEST, postpasswordchangeRequest, api),
    takeLatest(CommunityTypes.POSTUNFOLLOW_REQUEST, postunfollowRequest, api),
    takeLatest(CommunityTypes.POSTCONNECTIONUPDATE_REQUEST, postconnectionupdateRequest, api),
    takeLatest(CommunityTypes.POSTREGISTERUSER_REQUEST, postregisteruserRequest, api),
    takeEvery(CommunityTypes.GETTOPICS_REQUEST, gettopicsRequest, api),
    takeLatest(CommunityTypes.GETCOMBLOGPOSTS_REQUEST, getcomblogpostsRequest, api),
    takeLatest(CommunityTypes.GETEDITFEATUREDITEMS_REQUEST, geteditfeatureditemsRequest, api),
    takeLatest(CommunityTypes.GETFEATUREDITEMS_REQUEST, getfeatureditemsRequest, api),
    takeEvery(CommunityTypes.GETCATEGORYSPONSOREDPRODUCTS_REQUEST, getcategorysponsoredproductsRequest, api),
    takeLatest(CommunityTypes.POSTSAVECOMMENT_REQUEST, postsavecommentRequest, api),
  ])
}
